sudo: required
services:
  - docker

before_install:
  - docker build -t theotan/docker-react -f Dockerfile.dev .

script:
  - docker run theotan/docker-react npm run test -- --watchAll=false --coverage